export const EMAIL_FAQS = [
  { question: "What is included in your email marketing service?", answer: "The scope can include strategy, list audit, segmentation, copywriting, responsive campaign design, platform setup, automation, testing, deliverability support and reporting. The final mix is shaped around your goals and current setup." },
  { question: "Which email marketing platforms can you work with?", answer: "We can work with widely used email, CRM and ecommerce platforms. We confirm the best setup after reviewing your subscriber data, automation needs, integrations, team workflow and existing technology." },
  { question: "Can you create newsletters and automated journeys?", answer: "Yes. We create one-time campaigns and recurring newsletters as well as welcome, nurture, cart recovery, post-purchase, retention and re-engagement automations." },
  { question: "Do you provide the email copy and design?", answer: "Yes. Campaign production can include subject lines, preheaders, body copy, calls to action and responsive branded design. Landing pages or advanced custom assets can also be scoped when required." },
  { question: "How do you protect email deliverability?", answer: "We use permission-based practices, list hygiene, authentication guidance, sensible sending patterns and pre-send checks. Deliverability also depends on your list sources, domain history, platform and subscriber engagement." },
  { question: "How quickly can email marketing show results?", answer: "Campaign engagement can be visible after the first send, while automation and lifecycle improvement build over time. The timeline depends on list quality, audience size, offer, traffic and the amount of usable customer data." },
  { question: "How is email performance reported?", answer: "Reporting focuses on the agreed objective and may include delivery, clicks, conversions, revenue, list growth, unsubscribes and automation performance, followed by practical recommendations for the next cycle." },
  { question: "Can email connect with our website, CRM or store?", answer: "Yes. Depending on your stack, email can connect with website forms, CRM stages, product catalogues, ecommerce behavior, lead sources and conversion tracking. Integration scope is confirmed after a technical review." },
];
